QuizMaster/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuizMaster.Data;
using QuizMaster.Models;
using QuizMaster.ViewModels;

namespace QuizMaster.Controllers
{
    public class CandidateController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public CandidateController(ApplicationDbContext context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }

        public async Task<ActionResult> AllCandidates()
        {
            var candidate = await _context.Candidates.ToListAsync();
            if(candidate != null)
            {
                return View(candidate);
            }
            else
            {
                TempData["NullScore"] = "There is no registered candidate yet";
                return View("Index", "Home");
            }
        }

        // GET: Candidate/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Candidate/Create
        public ActionResult CreateCandidate()
        {
            return View();
        }

        // POST: Candidate/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCandidate(CandidateViewModel Vmodel)
        {
            try
            {
                var examCode = DateTime.Now.ToString().Replace("/", "").Replace(":", "").Replace("AM", "00").Replace("PM", "1").Replace(" ", "");
                var candidate = new Candidate
                {
                    Name = Vmodel.Name,
                    Email = Vmodel.Email,
                    ExamCode = examCode,
                    Phone = Vmodel.Phone,
                    RegistrationDate = DateTime.Now

                };
                var emailMessage = $"Dear {candidate.Name} your registration was sucessfull, you can visit our page for your exam. use {candidate.ExamCode} to login";
                var result = _context.Candidates.Where(x => x.Email == candidate.Email).FirstOrDefault();
                if (result == null)
                {
                    await _context.Candidates.AddAsync(candidate);
                    await _context.SaveChangesAsync();
                    await _emailSender.SendEmailAsync(candidate.Email, "Quiz Master Registration", emailMessage);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Message = "User with this Email Already Exist";
                    return View();
                }

            }
            catch
            {
                return View();
            }
        }


        // GET: Candidate/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Candidate/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Candidate/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Candidate/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

QuizMaster/Controllers/QuizManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuizMaster.Data;
using QuizMaster.Models;
using QuizMaster.Services;
using QuizMaster.ViewModels;

namespace QuizMaster.Controllers
{
    [System.Runtime.InteropServices.Guid("4ED32701-1C16-4D87-BB82-0BE69348E67F")]
    public class QuizManagerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _context;
        public QuizManagerController(IUnitOfWork unitOfWork, ApplicationDbContext context)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }
        [HttpGet]
        public IActionResult ErrorPage(string message)
        {
            if (!string.IsNullOrEmpty(message))
                TempData["ErrorMessage"] = message;
            return View();


        }

        [HttpGet]
        public IActionResult ValidateCandidate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ValidateCandidate(CandidateValidationViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var candidate = await _context.Candidates.Where(x => x.Email.Contains(viewModel.Email) && x.ExamCode.Contains(viewModel.ExamCode)).FirstOrDefaultAsync();
                if (candidate != null)
                {
                    HttpContext.Session.SetString("sessionExamCode", candidate.ExamCode);
                    HttpContext.Session.SetString("sessionEmail", candidate.Email);
                    HttpContext.Session.SetString("sessionName", candidate.Name);
                    HttpContext.Session.SetInt32("sessionId", candidate.Id);
                    if (HttpContext.Session.GetString("sessionEmail") != null)
                    {
                        return RedirectToAction(nameof(Instruction));
                    }

                }
                ViewBag.ErrorMessage = "Your Details are not found";
                //return NotFound("Your Details are not found");
                return RedirectToAction("ErrorPage", new { message = "We could not verify your credentials. Please double-check and try again" });
            }
            return View();
        }
        [HttpGet]
        public IActionResult Instruction()
        {
            ViewBag.QuestionCount = _context.Questions.Count();
            ViewBag.Name = HttpContext.Session.GetString("sessionName");
            return View();
        }
        [HttpPost]
        public IActionResult Instruction(string name)
        {
            var examCode = HttpContext.Session.GetString("sessionExamCode");
            var examStatus = _context.Examinations.Where(x => x.ExamCode.Contains(examCode)).FirstOrDefault();
            if (examStatus == null)
            {
                return RedirectToAction(nameof(TakeExam));
            }
            return RedirectToAction("ErrorPage", new { message = "Quiz is no more available for this candidate, Contact the Admin!" });
        }

        [HttpGet]
        public IActionResult CreatSubject()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreatSubject(Subject model)
        {
            var IsExist = _context.Subjects.Where(x => x.Name == model.Name).FirstOrDefault();
            if (IsExist == null)
            {
                _unitOfWork.AddSubject(model);
                await _unitOfWork.Save();
                return RedirectToAction(nameof(CreatSubject));
            }
            else
            {
                ViewBag.Message = "Subject Name Already Exist";
                return View();
            }

        }
        public IActionResult CreatQuestion()
        {
            ViewBag.Subject = _unitOfWork.GetSubjects();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreatQuestion(Question model)
        {
            _unitOfWork.AddQuestion(model);
            await _unitOfWork.Save();
            return View();
        }
        public IActionResult CreatExam()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatExam(Examination model)
        {
            _unitOfWork.AddExam(model);
            await _unitOfWork.Save();
            return View();
        }
        [HttpGet]
        public IActionResult TakeExam()
        {
            var examCode = HttpContext.Session.GetString("sessionExamCode");
            var examcount = _context.Examinations.Where(x => x.ExamCode == examCode).Count();
            var questionCount = _context.Questions.Count();
            var id = examcount + 1;
            ViewBag.Question = _context.Questions.Where(x => x.QuestionNumber == id).ToList();
            ViewBag.count = id;
            ViewBag.Value = _context.Questions.Count();
            ViewBag.Max = _context.Examinations.Count();
            ViewBag.ExamCount = id;



            if (HttpContext.Session.GetString("sessionEmail") != null)
            {

                if (examcount != questionCount)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction(nameof(CalculateScores));
                }
            }
            return RedirectToAction("ErrorPage", new { message = "Section has Expired" });

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TakeExam(ExaminationViewModel Vmodel)
        {
            if (ModelState.IsValid)
            {
                var examcount = _context.Examinations.Count();
                var questionCount = _context.Questions.Count();
                var model = new Examination
                {
                    Option = Vmodel.Option,
                    Answer = Vmodel.Answer,
                    QuestionId = Vmodel.QuestionId,
                    CandidateId = (int)HttpContext.Session.GetInt32("sessionId"),
                    ExamCode = HttpContext.Session.GetString("sessionExamCode"),
                };
                await _context.Examinations.AddAsync(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(TakeExam));

            };
            return RedirectToAction("ErrorPage", new { message = "Error has Occured" });

        }


        public async Task<IActionResult> CalculateScores()
        {

            var examCode = HttpContext.Session.GetString("sessionExamCode");
            var candidateName = HttpContext.Session.GetString("sessionName");
            var pass = _context.Examinations.Where(x => x.Answer == x.Option && x.ExamCode == examCode).Count();
            var fail = _context.Examinations.Where(x => x.Answer != x.Option && x.ExamCode == examCode).Count();
            var Total = _context.Examinations.Where(x => x.ExamCode == examCode).Count();
            var percentageScore = (pass / Total) / 100;
            ViewBag.Pass = pass;
            ViewBag.Fail = fail;
            ViewBag.Total = Total;
            ViewBag.PercentageScore = percentageScore;
            ViewBag.Score = _context.Examinations.Where(x => x.Answer == x.Option && x.ExamCode == examCode).Count();
            var score = new Score
            {
                ExamCode = examCode,
                CandidateName = candidateName,
                CandidateScore = pass,
                TestDate = DateTime.Now
            };
            if (ModelState.IsValid)
            {
                try
                {
                    await _context.Scores.AddRangeAsync(score);
                    await _context.SaveChangesAsync();

                    return View();
                }
                catch
                {
                    return RedirectToAction("ErrorPage", new { message = "Error has Occured" });
                }

            }
            else
            {
                return RedirectToAction("ErrorPage", new { message = "Invalid Query" });
            }
        }
        public async Task<IActionResult> AllScore()
        {
            var scores = await _context.Scores.ToListAsync();
            if(scores != null)
            {
                return View(scores);
            }
            TempData["NullScore"] = "There is no score available";
            return View("Index", "Home");
        }

        [HttpGet]
        public IActionResult GetScore()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetScore(Score score)
        {
            await _context.Scores.Where(x => x.ExamCode == score.ExamCode).FirstOrDefaultAsync();
            var scores = await _context.Scores.ToListAsync();
            return View(scores);
        }


        [HttpGet]
        public IActionResult TakeExams()
        {
            var examCode = HttpContext.Session.GetString("sessionExamCode");
            var examcount = _context.Examinations.Where(x => x.ExamCode == examCode).Count();
            var questionCount = _context.Questions.Count();
            var id = examcount + 2;
            ViewBag.Question = _context.Questions.Where(x => x.QuestionNumber == id).ToList();
            ViewBag.count = id;
            ViewBag.Value = _context.Questions.Count();
            ViewBag.Max = _context.Examinations.Count();


            if (HttpContext.Session.GetString("sessionEmail") != null)
            {

                if (examcount != questionCount)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction(nameof(CalculateScores));
                }
            }
            return RedirectToAction("ErrorPage", new { message = "Session has expired" });

QuizMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizMaster</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="stylesheet" href="~/css/notFound.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/style.css">

</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuizMaster</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@





                <div class="container-fluid px-md-5  pt-4 pt-md-5">
                    <div class="row justify-content-between">
                        <div class="col-md-8 order-md-last">
                            <div class="row">
                                <div class="col-md-6 text-center">
                                    <a class="navbar-brand" href="index.html">Learning <span>Hub</span> <small>E-Learning Company</small></a>
                                </div>
                                <div class="col-md-6 d-md-flex justify-content-end mb-md-0 mb-3">
                                    <form action="#" class="searchform order-lg-last">
                                        <div class="form-group d-flex">
                                            <input type="text" class="form-control pl-3" placeholder="Search">
                                            <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-flex">
                            <div class="social-media">
                                <p class="mb-0 d-flex">
                                    <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                                    <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                                    <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
                                    <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
                    <div class="container-fluid">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="fa fa-bars"></span> Menu
                        </button>
                        <div class="collapse navbar-collapse" id="ftco-nav">
                            <ul class="navbar-nav m-auto">
                                <li class="nav-item active"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                                <li class="nav-item"><a href="#" class="nav-link">About</a></li>
                                <li class="nav-item"><a asp-action="CreateCandidate" asp-controller="Candidate" class="nav-link">New Candidate</a></li>

                                <li class="nav-item"><a href="#" class="nav-link">Books</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Admin
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="QuizManager" asp-action="CreatSubject">Add subject</a>
                                        <a class="dropdown-item" asp-controller="QuizManager" asp-action="CreatQuestion">Add Question</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-controller="Candidate" asp-action="AllCandidates">Candidates</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Quiz
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="QuizManager" asp-action="ValidateCandidate">Take Quiz</a>
                                        <a class="dropdown-item" asp-controller="QuizManager" asp-action="AllScore">Check score action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-controller="Candidate" asp-action="CreateCandidate">Register as Candidate</a>
                                    </div>
                                </li>


                                <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="@*ftco-footer*@">
        
        <div class="container-fluid px-0 py-5 bg-black">
            <div class="container">
                <div class="col-md-12 d-flex">
                    <div class="social-media">
                        <p class="mb-0 d-flex">
                            <a href="https://www.facebook.com/reginald.ozougwu" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                            <a href="https://twitter.com/reginald160" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                            <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
                            <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
                        </p>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-12">

                        <p class="mb-0" style="color: rgba(255,255,255,.5);">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | Ginatech Global services <i class="fa fa-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Ginatech.com</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/scrollax.min.js"></script>

    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>